### PR TITLE
Make gzip read as much gzip data as possible before moving on instead of causing an exception.

### PR DESCRIPTION
**Pull request by keithjjones**
Hi,

Thanks for this great library.  I have several Zeek logs that have some corrupted data at the end when Zeek restarts ungracefully and this change will read as much data as possible from a compressed log before moving on to the next log.

Thanks!

### CODE REVIEW

**Comment by brifordwylie** [comment]
Thanks @keithjjones the patch/improvement looks good.... not sure why the auto build isn't working... I'll poke at it and then merge your PR. I do have a request... can we pin down the exception like `IOError` or whatever is getting thrown.. .since you have the corrupt gzip files probably easier for you to figure these out (there might be multiple) or you can email me an example (hopefully smallish) to support@supercowpowers.com

**Comment by brifordwylie** [comment]
Not sure why Github build/check isn't reporting back... shrug.. I'll probably just merge this PR and then make another one with the specific exceptions and see if the github build 'wakes up'.

**Comment by brifordwylie** [comment]
hi @keithjjones so I'm looking at this a bit closer.. 

The current (pre PR) functionality is just 'unzipping' the file and then sending that to the normal zeek log reader...

```
    shutil.copyfileobj(f_in, f_out)
```
Then the normal log reader ^should^ read in each line and gracefully fail when reading a line goes awry...

```
  while True:
            # Yield the rows from the internal reader
            try:
                for row in self._readrows():
                    if reconnecting:
                        print('Successfully monitoring {:s}...'.format(self._filepath))
                        reconnecting = False
                    yield row
            except IOError:
                # If the tail option is set then we do a retry (might just be a log rotation)
                if self._tail:
                    print('Could not open file {:s} Retrying...'.format(self._filepath))
                    reconnecting = True
                    time.sleep(5)
                    continue
                else:
                    break
  ```
So I'm not entirely sure why the existing code isn't working... would you be able to provide an example of a corrupt gzip file? Please send to support@supercowpowers.com we will obviously only use the file for our internal testing...

**Comment by keithjjones** [comment]
@brifordwylie unfortunately I can't share the logs because they are files with real network data on a customer's network.  I don't have a way to reproduce it on a public pcap right now.

I reproduced the error in zat v0.4.4 on the customer data that has the missing end of file:

```
Traceback (most recent call last):
  File "graph.py", line 253, in <module>
    load_data()
  File "graph.py", line 137, in load_data
    for row in reader.readrows():
  File "/data/home/keith/python/3/lib/python3.8/site-packages/zat/zeek_multi_log_reader.py", line 43, in readrows
    shutil.copyfileobj(f_in, f_out)
  File "/usr/lib/python3.8/shutil.py", line 205, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.8/gzip.py", line 498, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

graph.py is my program.  The EOFError exception happens in ` shutil.copyfileobj(f_in, f_out)`, so that's why I did the line by line trick to get around that function.  I also don't know if there are other exceptions we should be watching for, so that's why I tried to catch exceptions generally in the fix.

**Comment by brifordwylie** [comment]
@keithjjones okay... thanks for the exception stack it really helps 👍  I think given this information I can construct a test case that will hit the same exception. I'll keep you in the loop.

**Comment by keithjjones** [comment]
@brifordwylie I noticed there isn't a new version of the package.  It's still on 0.4.4 from before the change.  Is it possible to cut a new version 0.4.5 so pip can pull the latest code easily?  I've had to install it by cloning the repo and pushing it out to my remote machines, which takes a bit more work.  Thanks!

**Comment by brifordwylie** [comment]
Hi @keithjjones yeah sorry... completely pegged out on consulting work..so that's good news but means I'm struggling with ZAT support.. will try to get to new release this weekend. :)

**Comment by brifordwylie** [comment]
@keithjjones Okay.. pushed 0.4.5 to PyPI... I've added a test for a corrupt gzip file and some data for that test... seems to be working AOK... please give it a try and let me know...

```
Exception in ../data/http.log.corrupt.gz : Compressed file ended before the end-of-stream marker was reached
```

**Comment by keithjjones** [comment]
@brifordwylie 0.4.5 pulled fine for me!  Thanks!

**Pull request merged**
